# Site settings
title: FlipSkills
description: > # this means to ignore newlines until "email:"
  We work with organizations all over the globe to fuel collaboration, 
  enhance creativity, and develop today’s essential workplace capabilities: 
  Followership, Leadership, innovation & Partnership skills.
email: info@flipskills.com
phone_number: 647-296-6054
address: > # this means to ignore newlines until "url:"
  Liberty Village
  Toronto, ON
  Canada

url: "http://flipskills.github.io"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Prose metadata config
prose:
  metadata:
    _posts:
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          value: "ideasletter"
      - name: "title"
        field:
          element: "text"
          label: "title"
          placeholder: "Add The Full Title Here"
      - name: "date"
        field:
          element: "date"
          label: "yyyy-mm-dd hh-mm-ss"
          value: CURRENT_DATETIME
      - name: "vol"
        field:
          element: "text"
          label: "Volume"
          placeholder: "Jan 2017 - Vol 1, Issue 1"
      - name: "categories"
        field:
          element: "hidden"
          value: "ideasletter"
      - name: "img"
        field:
          element: "text"
          label: "Image Path"
          placeholder: "/images/ideasletter/default.png"
      - name: "introduction"
        field:
          element: "text"
          label: "title"
          placeholder: "Add The Description Here"
